# Generated by Django 4.2.6 on 2024-10-27 21:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(default='', max_length=64)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('bio', models.TextField()),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('profile_image', models.TextField(blank=True, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('last_date_online', models.DateTimeField(blank=True, null=True)),
                ('channel_name', models.CharField(blank=True, max_length=256, null=True)),
                ('is_channel_busy', models.BooleanField(blank=True, default=False, null=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('friends', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.CharField(default='<function uuid4 at 0x00000219EB96A7A0>', editable=False, max_length=124, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('group_name', models.CharField(max_length=120)),
                ('group_photo', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='all_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.CharField(default='<function uuid4 at 0x00000219EB96A7A0>', editable=False, max_length=124, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('video', models.TextField(blank=True, null=True)),
                ('audio', models.TextField(blank=True, null=True)),
                ('is_receipient_online', models.BooleanField(default=False)),
                ('likes', models.IntegerField(default=0)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='justChat_api.group')),
                ('receipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inbox', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IsGroupAdmin',
            fields=[
                ('is_group_admin_id', models.CharField(default='<function uuid4 at 0x00000219EB96A7A0>', editable=False, max_length=124, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('IsGroupAdmin', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_group_admin', to='justChat_api.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_group_admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
