# Generated by Django 4.2.6 on 2024-10-28 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justChat_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_id',
            field=models.CharField(default='<function uuid4 at 0x000002A3AF5AA7A0>', editable=False, max_length=124, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='isgroupadmin',
            name='is_group_admin_id',
            field=models.CharField(default='<function uuid4 at 0x000002A3AF5AA7A0>', editable=False, max_length=124, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.CharField(default='e1b1cd17-69c1-4933-84f5-b9f50415b7be', editable=False, max_length=124, primary_key=True, serialize=False),
        ),
    ]
