# Generated by Django 4.2.6 on 2025-01-07 16:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('justChat_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=124, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='isgroupadmin',
            name='is_group_admin_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=124, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.CharField(editable=False, max_length=124, primary_key=True, serialize=False),
        ),
    ]
