# Generated by Django 4.2.6 on 2024-10-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justChat_api', '0012_alter_isgroupadmin_is_group_admin_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='isgroupadmin',
            name='is_group_admin_id',
            field=models.CharField(default='<function uuid4 at 0x000001A4E616A7A0>', editable=False, max_length=124, primary_key=True, serialize=False),
        ),
    ]
