# Generated by Django 4.2.6 on 2025-01-03 21:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('justChat_api', '0013_message_file_alter_isgroupadmin_is_group_admin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isgroupadmin',
            name='is_group_admin_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=124, primary_key=True, serialize=False),
        ),
    ]
